version: '3'

services:
  elasticsearch:
    image: ${OSS_IMAGE}
    hostname: elasticsearch
    container_name: elasticsearch
    networks:
      - elasticsearch # used by ESv6 kibana
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - path.repo=/tmp
      - network.publish_host=127.0.0.1
      - logger.org.elasticsearch=warn
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ${OSS_ENV_VAR:-FOO=bar}
    command: ${ES_COMMAND}
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  xpack:
    image: ${XPACK_IMAGE:-alpine}
    hostname: elasticsearch-xpack
    container_name: elasticsearch-xpack
    environment:
      - cluster.name=xpack
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - path.repo=/tmp
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.watcher.enabled=true
      - http.port=9210
      - network.publish_host=127.0.0.1
      - logger.org.elasticsearch=warn
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=elastic
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9210:9210
  opendistro:
    image: ${ES_OPENDISTRO_IMAGE:-alpine}
    hostname: elasticsearch-opendistro
    container_name: elasticsearch-opendistro
    environment:
      - cluster.name=opendistro
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - path.repo=/tmp
      - ${OPENSEARCH_PREFIX:-opendistro_security}.ssl.http.enabled=false
      - http.port=9220
      - network.publish_host=127.0.0.1
      - logger.org.elasticsearch=warn
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9220:9220
  xpack-kibana:
    image: ${XPACK_IMAGE:-alpine}
    networks:
      - elasticsearch  # used by ESv7 kibana
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.port=9230
      - logger.org.elasticsearch=warn
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1g
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9230:9230
  kibana:
    image: ${ES_KIBANA_IMAGE:-alpine}
    networks:
      - elasticsearch
    links:
      - xpack-kibana
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: aaaa1111bbbb2222cccc3333dddd4444
      ELASTICSEARCH_HOSTS: http://xpack-kibana:9230
    depends_on:
      - elasticsearch
      - xpack-kibana
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
networks:
  elasticsearch:
    driver: bridge
